CREATE TABLE calibrationdetails
(
  CALIBRATION_ID    VARCHAR(10) NOT NULL,
  NOMINAL_SIZE      DECIMAL(10,3) NOT NULL,
  ACTUAL_MEASURED_1 DECIMAL(10,3),
  ACTUAL_MEASURED_2 DECIMAL(10,3),
  ACTUAL_MEASURED_3 DECIMAL(10,3),
  TMSTP_ENTERED     DATETIME,
  ID_USER_ENTERED   VARCHAR(10),
  TMSTP_MODIFIED    DATETIME,
  ID_USER_MODIFIED  VARCHAR(10),
  PRIMARY KEY (CALIBRATION_ID, NOMINAL_SIZE)
);

-- Creating table calibrationmaster
CREATE TABLE calibrationmaster
(
  CALIBRATION_ID   VARCHAR(10) NOT NULL,
  REFERENCE_NO     VARCHAR(5),
  REFERENCE_DATE   DATE,
  INSTRUMENT_ID    VARCHAR(10) NOT NULL,
  CALIBRATION_DATE DATE,
  TMSTP_ENTERED    DATETIME,
  ID_USER_ENTERED  VARCHAR(10),
  TMSTP_MODIFIED   DATETIME,
  ID_USER_MODIFIED VARCHAR(10),
  SLIP_GAUGE_ID    VARCHAR(10) NOT NULL,
  IND_PRINT        VARCHAR(1),
  TEMP             DECIMAL(6,0),
  HUMIDITY         DECIMAL(6,0),
  PRIMARY KEY (CALIBRATION_ID)
);

-- Creating table customermaster
CREATE TABLE customermaster
(
  CUSTOMER_ID      VARCHAR(10) NOT NULL,
  CUSTOMER_DESC    VARCHAR(20) NOT NULL,
  TMSTP_ENTERED    DATETIME,
  ID_USER_ENTERED  VARCHAR(10),
  TMSTP_MODIFIED   DATETIME,
  ID_USER_MODIFIED VARCHAR(10),
  PRIMARY KEY (CUSTOMER_ID),
  UNIQUE KEY (CUSTOMER_DESC)
);

-- Creating table instrumentmaster
CREATE TABLE instrumentmaster
(
  INSTRUMENT_ID           VARCHAR(10) NOT NULL,
  CUSTOMER_ID             VARCHAR(10) NOT NULL,
  IDENTIFICATION_NO       VARCHAR(20) NOT NULL,
  DESCRIPTION             VARCHAR(50),
  CALIBRATION_RANGE       VARCHAR(8),
  ACTUAL_RANGE_CALIBRATED VARCHAR(8),
  MAKE                    VARCHAR(10),
  PERIODICITY             VARCHAR(10),
  LEAST_COUNT             DECIMAL(7,4),
  TMSTP_ENTERED           DATETIME,
  ID_USER_ENTERED         VARCHAR(10),
  TMSTP_MODIFIED          DATETIME,
  ID_USER_MODIFIED        VARCHAR(10),
  REF_STD                 VARCHAR(30),
  PRIMARY KEY (INSTRUMENT_ID),
  UNIQUE KEY (IDENTIFICATION_NO),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES customermaster (CUSTOMER_ID)
);

-- Creating table nominalsizes
CREATE TABLE nominalsizes
(
  INSTRUMENT_ID    VARCHAR(10) NOT NULL,
  NOMINAL_SIZE     DECIMAL(10,3) NOT NULL,
  TMSTP_ENTERED    DATETIME,
  ID_USER_ENTERED  VARCHAR(10),
  TMSTP_MODIFIED   DATETIME,
  ID_USER_MODIFIED VARCHAR(10),
  PRIMARY KEY (INSTRUMENT_ID, NOMINAL_SIZE)
);

-- Creating table slipgaugemaster
CREATE TABLE slipgaugemaster
(
  SLIP_GAUGE_ID    VARCHAR(10) NOT NULL,
  SERIAL_NO        VARCHAR(10),
  CERTIFICATE_NO   VARCHAR(25),
  CERTIFICATE_DATE DATE,
  WHETHER_OBSOLETE VARCHAR(1),
  TMSTP_ENTERED    DATETIME,
  ID_USER_ENTERED  VARCHAR(10),
  TMSTP_MODIFIED   DATETIME,
  ID_USER_MODIFIED VARCHAR(10),
  PRIMARY KEY (SLIP_GAUGE_ID)
);

-- Creating table slipgaugedetails
CREATE TABLE slipgaugedetails
(
  SLIP_GAUGE_ID       VARCHAR(10) NOT NULL,
  NOMINAL_SIZE        DECIMAL(10,3) NOT NULL,
  ERROR_IN_SLIP_GAUGE DECIMAL(10,3),
  TMSTP_ENTERED       DATETIME,
  ID_USER_ENTERED     VARCHAR(10),
  TMSTP_MODIFIED      DATETIME,
  ID_USER_MODIFIED    VARCHAR(10),
  PRIMARY KEY (SLIP_GAUGE_ID, NOMINAL_SIZE),
  FOREIGN KEY (SLIP_GAUGE_ID) REFERENCES slipgaugemaster (SLIP_GAUGE_ID)
);